apiVersion: v2
name: kd-cruise-stack
description: Parent chart to deploy the KD Cruise Ship App stack (API, PostgreSQL, Prometheus)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: "0.1.0"
    repository: "file://../postgresql"
  - name: planned-events-api
    version: "0.1.0" 
    repository: "file://../planned-events-api"
  - name: kube-prometheus-stack
    version: "75.9.0" 
    repository: "https://prometheus-community.github.io/helm-charts"
