apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kd-postgres
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/oyechr/kd-cruise'
    targetRevision: HEAD
    path: charts/postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
