apiVersion: v1
kind: Service
metadata:
  name: {{ include "planned-events-api.fullname" . }}
  labels:
    app: {{ include "planned-events-api.name" . }}
    release: prometheus  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "planned-events-api.name" . }}
