apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: {{ include "postgresql.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}  
  endpoints:
    - port: metrics
      interval: 1m
      path: /metrics
      scheme: http
      scrapeTimeout: 10s
      honorLabels: true
