apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "postgresql.name" . }}
