auth:
  username: kdadmin
  password: kdpass
  database: kdcruise

primary:
  initdb:
    scripts:
      init.sql: |-
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        CREATE TABLE IF NOT EXISTS planned_events_tab (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        voyage_id INT NOT NULL,
        vessel_id INT NOT NULL,
        from_date TIMESTAMP NOT NULL,
        to_date TIMESTAMP NOT NULL,
        event TEXT NOT NULL
        );
        INSERT INTO planned_events_tab (voyage_id, vessel_id, from_date, to_date, event)
        VALUES
            (123, 332, '2025-03-18 17:00:00', '2025-03-18 19:00:00', 'Dance at pool'),
            (123, 332, '2025-03-19 10:00:00', '2025-03-19 12:00:00', 'Morning Yoga'),
            (123, 332, '2025-03-19 14:00:00', '2025-03-19 16:00:00', 'Lunch Buffet'),
            (123, 332, '2025-03-19 18:00:00', '2025-03-19 20:00:00', 'Evening Concert'),
            (123, 332, '2025-03-20 08:00:00', '2025-03-20 10:00:00', 'Breakfast at Deck'),
            (123, 332, '2025-03-20 15:00:00', '2025-03-20 17:00:00', 'Afternoon Tea'),
            (123, 332, '2025-03-20 18:00:00', '2025-03-20 20:00:00', 'Sunset Cruise'),
            (123, 332, '2025-03-21 07:00:00', '2025-03-21 09:00:00', 'Early Bird Yoga'),
            (123, 332, '2025-03-21 19:00:00', '2025-03-21 21:00:00', 'Captain''s Dinner'),
            (123, 332, '2025-03-22 10:00:00', '2025-03-22 12:00:00', 'Island Excursion');
