name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "src/KD.Cruise.PlannedEventsApi/**"
      - "charts/**"
      - "monitoring/**"
      - ".github/workflows/docker-push.yaml"
jobs:
  build-and-push:
    name: Build & Push API Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image tag
        id: meta
        run: echo "image_tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/oyechr/planned-events-api:${{ steps.meta.outputs.image_tag }} \
                       -t ghcr.io/oyechr/planned-events-api:latest \
                       -f src/KD.Cruise.PlannedEventsApi/Dockerfile src
          docker push ghcr.io/oyechr/planned-events-api:${{ steps.meta.outputs.image_tag }}
          docker push ghcr.io/oyechr/planned-events-api:latest
