name: Build and Push Docker Image

on:
  push:
    branches: 
    - main
    paths:
      - 'src/KD.Cruise.PlannedEventsApi/**'
      - 'charts/planned-events-api/**'
      - '.github/workflows/docker-push.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: |
          IMAGE_TAG=sha-${GITHUB_SHA::7}
          docker build -t ghcr.io/oyechr/planned-events-api:$IMAGE_TAG .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/oyechr/planned-events-api:$IMAGE_TAG
